### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by kibotu** [gavingt/upcoming-games#1]
since you've asked so nicely on reddit

never hold static references on context classes on android, in fact static activity and application context is first example on memory leaks on android that you can find on the internet since 2009 

better check out leakcanary while you're at it :) 

https://github.com/gavingt/upcoming-games/blob/fef1223b8188f06766b431d3020dc445d006b8bd/app/src/main/java/com/gavinsappcreations/upcominggames/App.kt#L31-L35

the way you can resolve this is by using a weak reference, here is a library that does this quite well:
https://github.com/florent37/ApplicationProvider

and here is another example of how you can even access resources easier using this technique:

https://github.com/kibotu/AndroidResourceExtensions

good luck with your project

**Comment by gavingt** [comment]
Thanks for the feedback! I've made the necessary changes to enable removal of the static application context:
https://github.com/gavingt/upcoming-games/commit/cd7af7fbdd60933991ea7f8b966ca171bb594cb3

Is that an improvement?

I've also run LeakCanary. It's not reporting any leaks, so I think I'm good there.

EDIT: now it's reporting an Android library leak, but I think that one's unavoidable.

Thanks again!
